import * as types from './types'

export const GET_STAKING_INFO: types.GET_STAKING_INFO = 'GET_STAKING_INFO'
export const GET_STAKING_INFO_SUCCESS: types.GET_STAKING_INFO_SUCCESS = 'GET_STAKING_INFO_SUCCESS'
export const GET_STAKING_INFO_FAIL: types.GET_STAKING_INFO_FAIL = 'GET_STAKING_INFO_FAIL'

export const GET_CONNECTIONS_COUNT: types.GET_CONNECTIONS_COUNT = 'GET_CONNECTIONS_COUNT'
export const GET_CONNECTIONS_COUNT_SUCCESS: types.GET_CONNECTIONS_COUNT_SUCCESS = 'GET_CONNECTIONS_COUNT_SUCCESS'
export const GET_CONNECTIONS_COUNT_FAIL: types.GET_CONNECTIONS_COUNT_FAIL = 'GET_CONNECTIONS_COUNT_FAIL'

export const GET_BLOCK_COUNT: types.GET_BLOCK_COUNT = 'GET_BLOCK_COUNT'
export const GET_BLOCK_COUNT_SUCCESS: types.GET_BLOCK_COUNT_SUCCESS = 'GET_BLOCK_COUNT_SUCCESS'
export const GET_BLOCK_COUNT_FAIL: types.GET_BLOCK_COUNT_FAIL = 'GET_BLOCK_COUNT_FAIL'
