export const GET_STAKING_INFO = 'GET_STAKING_INFO'
export const SUCCESSFULLY_RETRIEVED_STAKING_INFO = 'SUCCESSFULLY_RETRIEVED_STAKING_INFO'
export const FAILED_TO_RETRIEVE_STAKING_INFO = 'FAILED_TO_RETRIEVE_STAKING_INFO'
