import * as types from './types'

export const INITIALIZE_ELECTRA: types.INITIALIZE_ELECTRA = 'INITIALIZE_ELECTRA'
export const INITIALIZE_ELECTRA_FAIL: types.INITIALIZE_ELECTRA_FAIL = 'INITIALIZE_ELECTRA_FAIL'
export const INITIALIZE_ELECTRA_SUCCESS: types.INITIALIZE_ELECTRA_SUCCESS = 'INITIALIZE_ELECTRA_SUCCESS'

export const GENERATE_HARD_WALLET: types.GENERATE_HARD_WALLET = 'GENERATE_HARD_WALLET'
export const GENERATE_HARD_WALLET_FAIL: types.GENERATE_HARD_WALLET_FAIL = 'GENERATE_HARD_WALLET_FAIL'
export const GENERATE_HARD_WALLET_SUCCESS: types.GENERATE_HARD_WALLET_SUCCESS = 'GENERATE_HARD_WALLET_SUCCESS'

export const START_DAEMON: types.START_DAEMON = 'START_DAEMON'
export const START_DAEMON_FAIL: types.START_DAEMON_FAIL = 'START_DAEMON_FAIL'
export const START_DAEMON_SUCCESS: types.START_DAEMON_SUCCESS = 'START_DAEMON_SUCCESS'

export const STOP_DAEMON: types.STOP_DAEMON = 'STOP_DAEMON'
export const STOP_DAEMON_FAIL: types.STOP_DAEMON_FAIL = 'STOP_DAEMON_FAIL'
export const STOP_DAEMON_SUCCESS: types.STOP_DAEMON_SUCCESS = 'STOP_DAEMON_SUCCESS'

export const UNLOCK_WALLET: types.UNLOCK_WALLET = 'UNLOCK_WALLET'
export const UNLOCK_WALLET_FAIL: types.UNLOCK_WALLET_FAIL = 'UNLOCK_WALLET_FAIL'
export const UNLOCK_WALLET_SUCCESS: types.UNLOCK_WALLET_SUCCESS = 'UNLOCK_WALLET_SUCCESS'
