export const INITIALIZE_ELECTRA = 'INITIALIZE_ELECTRA'
export const INITIALIZE_ELECTRA_SUCCESS = 'INITIALIZE_ELECTRA_SUCCESS'
export const INITIALIZE_ELECTRA_FAIL = 'INITIALIZE_ELECTRA_FAIL'

export const GENERATE_HARD_WALLET = 'GENERATE_HARD_WALLET'
export const SUCCESSFULLY_GENERATED_HARD_WALLET = 'SUCCESSFULLY_GENERATED_HARD_WALLET'
export const FAILED_T0_GENERATE_HARD_WALLET = 'FAILED_T0_GENERATE_HARD_WALLET'
