import * as types from './types'

export const INITIALIZE_ELECTRA: types.INITIALIZE_ELECTRA = 'INITIALIZE_ELECTRA'
export const INITIALIZE_ELECTRA_FAIL: types.INITIALIZE_ELECTRA_FAIL = 'INITIALIZE_ELECTRA_FAIL'
export const INITIALIZE_ELECTRA_SUCCESS: types.INITIALIZE_ELECTRA_SUCCESS = 'INITIALIZE_ELECTRA_SUCCESS'

export const GENERATE_HARD_WALLET: types.GENERATE_HARD_WALLET = 'GENERATE_HARD_WALLET'
export const GENERATE_HARD_WALLET_FAIL: types.GENERATE_HARD_WALLET_FAIL = 'GENERATE_HARD_WALLET_FAIL'
export const GENERATE_HARD_WALLET_SUCCESS: types.GENERATE_HARD_WALLET_SUCCESS = 'GENERATE_HARD_WALLET_SUCCESS'
