import * as types from './types'

export const SET_OPENED: types.SET_OPENED = 'SET_OPENED'
export const SET_UNLOCKED: types.SET_UNLOCKED = 'SET_UNLOCKED'
export const SET_UNLOCKED_SUCCESS: types.SET_UNLOCKED_SUCCESS = 'SET_UNLOCKED_SUCCESS'
export const SET_UNLOCKED_FAIL: types.SET_UNLOCKED_FAIL = 'SET_UNLOCKED_FAIL'
export const SET_LOCKED_SUCCESS: types.SET_LOCKED_SUCCESS = 'SET_LOCKED_SUCCESS'
export const SET_LOCKED_FAIL: types.SET_LOCKED_FAIL = 'SET_LOCKED_FAIL'
