import * as types from './types'

export const GET_GLOBAL_BALANCE: types.GET_GLOBAL_BALANCE = 'GET_GLOBAL_BALANCE'
export const GET_GLOBAL_BALANCE_SUCCESS: types.GET_GLOBAL_BALANCE_SUCCESS = 'GET_GLOBAL_BALANCE_SUCCESS'
export const GET_GLOBAL_BALANCE_FAIL: types.GET_GLOBAL_BALANCE_FAIL = 'GET_GLOBAL_BALANCE_FAIL'
