import * as types from './types'

export const GET_GLOBAL_BALANCE: types.GET_GLOBAL_BALANCE = 'GET_GLOBAL_BALANCE'
export const GET_GLOBAL_BALANCE_SUCCESS: types.GET_GLOBAL_BALANCE_SUCCESS = 'GET_GLOBAL_BALANCE_SUCCESS'
export const GET_GLOBAL_BALANCE_FAIL: types.GET_GLOBAL_BALANCE_FAIL = 'GET_GLOBAL_BALANCE_FAIL'

export const GET_CURRENT_PRICE_USD: types.GET_CURRENT_PRICE_USD = 'GET_CURRENT_PRICE_USD'
export const GET_CURRENT_PRICE_USD_SUCCESS: types.GET_CURRENT_PRICE_USD_SUCCESS = 'GET_CURRENT_PRICE_USD_SUCCESS'
export const GET_CURRENT_PRICE_USD_FAIL: types.GET_CURRENT_PRICE_USD_FAIL = 'GET_CURRENT_PRICE_USD_FAIL'

export const GET_CURRENT_PRICE_BTC: types.GET_CURRENT_PRICE_BTC = 'GET_CURRENT_PRICE_BTC'
export const GET_CURRENT_PRICE_BTC_SUCCESS: types.GET_CURRENT_PRICE_BTC_SUCCESS = 'GET_CURRENT_PRICE_BTC_SUCCESS'
export const GET_CURRENT_PRICE_BTC_FAIL: types.GET_CURRENT_PRICE_BTC_FAIL = 'GET_CURRENT_PRICE_BTC_FAIL'
