import * as types from './types'

export const SEND_ECA: types.SEND_ECA = 'SEND_ECA'
export const SEND_ECA_SUCCESS: types.SEND_ECA_SUCCESS = 'SEND_ECA_SUCCESS'
export const SEND_ECA_FAIL: types.SEND_ECA_FAIL = 'SEND_ECA_FAIL'

export const SET_TO_ADDRESS: types.SET_TO_ADDRESS = 'SET_TO_ADDRESS'
export const SET_AMOUNT: types.SET_AMOUNT = 'SET_AMOUNT'

export const GET_ADDRESSES: types.GET_ADDRESSES = 'GET_ADDRESSES'
export const GET_ADDRESSES_SUCCESS: types.GET_ADDRESSES_SUCCESS = 'GET_ADDRESSES_SUCCESS'
export const GET_ADDRESSES_FAIL: types.GET_ADDRESSES_FAIL = 'GET_ADDRESSES_FAIL'

export const CLEAR_SEND_CARD_FIELDS: types.CLEAR_SEND_CARD_FIELDS = 'CLEAR_SEND_CARD_FIELDS'
