import * as types from './types'

export const GET_TRANSACTIONS: types.GET_TRANSACTIONS = 'GET_TRANSACTIONS'
export const GET_TRANSACTIONS_LOOP: types.GET_TRANSACTIONS_LOOP = 'GET_TRANSACTIONS_LOOP'
export const GET_TRANSACTIONS_SUCCESS: types.GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS'
export const GET_TRANSACTIONS_FAIL: types.GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL'
export const GET_TRANSACTION: types.GET_TRANSACTION = 'GET_TRANSACTION'
